# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bot Framework
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 The Microsoft Bot Framework provides everything you need to build and connect your bots to your users wherever they converse – from sms to Office365 mail to Slack and more... It's your bot, where ever your users are talking.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
include: [_*.html]
exclude: [bot-connector-rest-api-reference.md,dev-portal-channel-configuration.md,build-docs.cmd,qnawizard-howto.md,qnawizard-overview.md]
lsi: false

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap